#!/usr/bin/env python
# Licensed under the Apache License, Version 2.0 (the \"License\");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from FOSS import armcontroller

def test_all_commands():
    ip_address = "192.168.4.1"  # Update this IP as per your device
    handler = armcontroller.RoArmM2S(ip_address)

    try:
        print("Testing CMD_WIFI_INFO:")
        print(handler.cmd_wifi_info())
        print(handler.open_jaw())
        print(handler.close_jaw())

        print("Testing CMD_LIGHT_CTRL:")
        print(handler.cmd_light_ctrl(255))
        print(handler.cmd_light_ctrl(0))
        sys.exit(0)

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    test_all_commands()
